//! Emit the built-in runtime constants `output.rs` holds.
//!
//! Upstream's build script either downloads prebuilt runtimes or builds them
//! for `wasm32-wasip2` with wasi-sdk and wasm-opt. Pane's vendored tree always
//! gets its runtime explicitly: `Runtime::Custom` with the committed
//! `tools/componentize-js/wasm-parts/runtime.wasm` (built for
//! `wasm32-wasip3` by `pane_js.py wasm-parts`, #215). Nothing in this
//! repository reads the built-in variants, and `pane-ext` embeds the committed
//! runtime exactly once (through `pane-build`), so the built-ins are empty
//! here rather than a second copy of the same bytes.
use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    for changed in ["src", "wit"] {
        println!(
            "cargo:rerun-if-changed={}",
            manifest_dir.join(changed).display()
        );
    }
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let output = "\
// Generated by build.rs: Pane always passes the runtime explicitly
// (Runtime::Custom with the committed wasm-parts/runtime.wasm), so the
// built-in variants are empty (see build.rs).
const DEFAULT_RUNTIME_WASM: &[u8] = &[];
const OPT_SIZE_RUNTIME_WASM: &[u8] = &[];
const DEFAULT_SYNC_RUNTIME_WASM: &[u8] = &[];
const OPT_SIZE_SYNC_RUNTIME_WASM: &[u8] = &[];
";
    fs::write(out_dir.join("output.rs"), output).expect("write output.rs");
}
